# Generated by Django 4.2.5 on 2023-09-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Forma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "surname",
                    models.CharField(blank=True, max_length=50, verbose_name="Фамилия"),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=50, verbose_name="Имя"),
                ),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Отчество"
                    ),
                ),
                (
                    "finish_year",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="Код окончания МИЭМ"
                    ),
                ),
                (
                    "op",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ИВТ", "ИВТ"),
                            ("ИТСС", "ИТСС"),
                            ("КБ", "КБ"),
                            ("ПМ", "ПМ"),
                            ("ИБ", "ИБ"),
                            ("Другое", "Другое"),
                            (None, "Направление подготовки не выбрано"),
                        ],
                        max_length=6,
                        verbose_name="ОП",
                    ),
                ),
                (
                    "yearrusa",
                    models.CharField(blank=True, max_length=50, verbose_name="Год"),
                ),
                (
                    "photo",
                    models.FileField(
                        null=True, upload_to="photorusa/", verbose_name="Фото в Рузе"
                    ),
                ),
                (
                    "job_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Ваше место работы"
                    ),
                ),
                (
                    "job_status",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Занимаемая должность в организации, компании",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "mail",
                    models.EmailField(
                        blank=True, max_length=100, verbose_name="Электронная почта"
                    ),
                ),
            ],
            options={
                "verbose_name": "Форма",
            },
        ),
    ]
